import type { NextPage } from 'next'
import Head from 'next/head'
import { AuthContextProvider } from '../context/auth/authcontext'


const Home: NextPage = () => {
  return (
    <AuthContextProvider>
      <div className='border-box'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* body */}
    </div>
    </AuthContextProvider>
    
  )
}

export default Home
